In [1]:
import numpy as np
import pandas as pd

training_dataset=pd.read_csv("train.csv")

training_dataset.drop('Name',axis=1,inplace=True)
training_dataset.drop('Cabin',axis=1,inplace=True)
training_dataset.drop('Ticket',axis=1,inplace=True)
training_dataset.drop('Embarked',axis=1,inplace=True)
x=training_dataset.iloc[: , 2:].values
y=training_dataset.iloc[: , 1].values

print(x)

[[3 'male' 22.0 1 0 7.25]
 [1 'female' 38.0 1 0 71.2833]
 [3 'female' 26.0 0 0 7.925]
 ...
 [3 'female' nan 1 2 23.45]
 [1 'male' 26.0 0 0 30.0]
 [3 'male' 32.0 0 0 7.75]]


In [2]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)

imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])

In [3]:
from sklearn.preprocessing import LabelEncoder
label_x=LabelEncoder()
x[:,1]=label_x.fit_transform(x[:,1])

from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()

x=sc_X.fit_transform(x)
print(x)

[[ 0.82737724  0.73769513 -0.5924806   0.43279337 -0.47367361 -0.50244517]
 [-1.56610693 -1.35557354  0.63878901  0.43279337 -0.47367361  0.78684529]
 [ 0.82737724 -1.35557354 -0.2846632  -0.4745452  -0.47367361 -0.48885426]
 ...
 [ 0.82737724 -1.35557354  0.          0.43279337  2.00893337 -0.17626324]
 [-1.56610693  0.73769513 -0.2846632  -0.4745452  -0.47367361 -0.04438104]
 [ 0.82737724  0.73769513  0.17706291 -0.4745452  -0.47367361 -0.49237783]]


/home/priyom/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [4]:
test_dataset=pd.read_csv("test.csv")

test_dataset.drop('Name',axis=1,inplace=True)
test_dataset.drop('Cabin',axis=1,inplace=True)
test_dataset.drop('Ticket',axis=1,inplace=True)
test_dataset.drop('Embarked',axis=1,inplace=True)
x_test=test_dataset.iloc[:, 1:].values
y_test=test_dataset.iloc[: , 1].values

print(x_test)

[[3 'male' 34.5 0 0 7.8292]
 [3 'female' 47.0 1 0 7.0]
 [2 'male' 62.0 0 0 9.6875]
 ...
 [3 'male' 38.5 0 0 7.25]
 [3 'male' nan 0 0 8.05]
 [3 'male' nan 1 1 22.3583]]


In [5]:
from sklearn.preprocessing import LabelEncoder
label_x_test=LabelEncoder()
x_test[:,1]=label_x_test.fit_transform(x_test[:,1])

In [6]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='median',axis=0)

imputer=imputer.fit(x_test[:,2:3])

x_test[:,2:3]=imputer.transform(x_test[:,2:3])
print(x_test)

x_test=sc_X.fit_transform(x_test)


[[3 1 34.5 0 0 7.8292]
 [3 0 47.0 1 0 7.0]
 [2 1 62.0 0 0 9.6875]
 ...
 [3 1 38.5 0 0 7.25]
 [3 1 27.0 0 0 8.05]
 [3 1 27.0 1 1 22.3583]]


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [7]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
regressor.predict(x_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').